$schema: https://azuremlschemas.azureedge.net/latest/data.schema.json

type: uri_file
name: used-cars-data
description: Dataset containing historical used car specifications and pricing features for MLOps pricing model training
path: ../used_cars.csv
